select * from customer limit 10;

--1) what is the total revenue generated by male VS female customers

select gender, Sum(purchase_amount) as revenue
from customer
group by gender;

--2)which customers used discount but still spent more than average purchase amount

select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= (select Avg(purchase_amount)
from customer);

--3)which are the top 5 products with highest average review rating

select item_purchased, Round(Avg(review_rating::numeric),2) as "Average product rating"
from customer
group by item_purchased
order by Avg(review_rating) desc
limit 5;

--4)compare the average purchase amount between standard and express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5) do subscribed customers spend more? compare avg spend and total revenue 
--between subscribers and non subscribers


select subscription_status,
count (customer_id) as total_customers,
Round(Avg(purchase_amount),2) as avg_spend,
Round(Sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--6)which 5 products have the highest percentage of purchases with discount applied

select item_purchased,
Round(100 * Sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2)
as discount_rate from customer
group by item_purchased
order by discount_rate desc
limit 5;

--7) segment customers into new, returning, loyal based on their toatal number of
--previous purchases and show the cout of each segment
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment;

--8) what are the top 3 most purchased products within each category

with items_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from items_counts
where item_rank <=3;

--9)are customers who are repeat buyers(more than 5 previous purchases)
--also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status


--10) what is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
